name: Deploy to GitHub Pages

on:
  push:
    branches:
      - test-branch  # Or the branch you're using

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This grants write access to contents
      pull-requests: write  # This grants write access to PRs if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          VITE_OPENWEATHER_API_KEY: ${{ secrets.VITE_OPENWEATHER_API_KEY }}
          VITE_HERE_API_KEY: ${{ secrets.VITE_HERE_API_KEY }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Adjust this if necessary
