name: Deploy to GitHub Pages

on:
  push:
    branches:
      - test-branch  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Check environment variables
        run: |
          echo "VITE_OPENWEATHER_API_KEY=${{ secrets.VITE_OPENWEATHER_API_KEY }}"
          echo "VITE_HERE_API_KEY=${{ secrets.VITE_HERE_API_KEY }}"

      - name: Build the project using Vite
        env:
          VITE_OPENWEATHER_API_KEY: ${{ secrets.VITE_OPENWEATHER_API_KEY }}
          VITE_HERE_API_KEY: ${{ secrets.VITE_HERE_API_KEY }}
        run: npm run build  # This should trigger Vite to build your app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # The directory where Vite outputs built files
