name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

        # Debugging step to check if the secrets are passed correctly
      - name: Check secret availability
        run: |
            echo "OPENWEATHER_API_KEY=${{ secrets.VITE_OPENWEATHER_API_KEY }}"
            echo "HERE_API_KEY=${{ secrets.VITE_HERE_API_KEY }}"

      - name: Build project
        env:
          VITE_OPENWEATHER_API_KEY: ${{ secrets.VITE_OPENWEATHER_API_KEY }}
          VITE_HERE_API_KEY: ${{ secrets.VITE_HERE_API_KEY }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Adjust to your build output directory
